Shop/Shop.Web/Controllers/OrdersController.cs
namespace Shop.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Shop.Web.Data;
    using Shop.Web.Data.Repositories;
    using Shop.Web.Models;

    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IProductRepository _productRepository;

        public OrdersController(IOrderRepository pOrderRepository,
                                IProductRepository productRepository)
        {
            this._orderRepository = pOrderRepository;
            this._productRepository = productRepository;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await _orderRepository.GetOrdersAsync(this.User.Identity.Name);
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = await this._orderRepository.GetDetailTempAsync(this.User.Identity.Name);
            return View(model);
        }


        [HttpGet]
        public IActionResult AddProduct()
        {
            var model = new AddItemViewModel
            {
                Quantity = 1,
                Products = this._productRepository.GetComboProducts() // select List 
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddProduct(AddItemViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await this._orderRepository.AddItemToOrderAsync(model, this.User.Identity.Name);
                return RedirectToAction("Create");
            }

            return View(model);
        }


        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this._orderRepository.DeleteDetailTempAsync(id.Value);
            return RedirectToAction("Create");
        }


        public async Task<IActionResult> Increase(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this._orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value, 1);
            return RedirectToAction("Create");
        }


        public async Task<IActionResult> Decrease(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this._orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value, -1);
            return RedirectToAction("Create");
        }


        public async Task<IActionResult> ConfirmOrder()
        {
            var resp = await this._orderRepository.ConfirmOrderAsync(this.User.Identity.Name);

            if (resp)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Create");
        }


        public async Task<IActionResult> Deliver(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await this._orderRepository.GetOrdersAsync(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            var model = new DeliverViewModel
            {
                Id = order.Id,
                DeliveryDate = DateTime.Today
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Deliver(DeliverViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await this._orderRepository.DeliverOrder(model);
                return this.RedirectToAction("Index");
            }

            return this.View();
        }

    }
}

Shop/Shop.Web/Controllers/ProductsController.cs
namespace Shop.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Data;
    using Data.Entities;
    using Models;
    using Helpers;
    using System.Threading.Tasks;
    using System.Linq;
    using Microsoft.AspNetCore.Authorization;

    public class ProductsController : Controller
    {
        private readonly IProductRepository _repos;
        private readonly IUserHelper _userHelper;
        private readonly IProductHelper _productHelper;

        public ProductsController(IProductRepository pRepos, IUserHelper pUserHelper, IProductHelper pProductHelper)
        {
            this._repos = pRepos;
            this._userHelper = pUserHelper;
            this._productHelper = pProductHelper;
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View(this._repos.GetAll().OrderBy(x => x.Name));
        }


        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var product = await this._repos.GetByIdAsync(id.Value);

            if (product == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            return View(product);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel productVM)
        {
            if (ModelState.IsValid)
            {
                string src = string.Empty;

                if (productVM.ImageFile != null && productVM.ImageFile.Length > 0)
                {
                    src = await this._productHelper.SaveImageAsync(productVM);
                }

                var user = await this._userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                productVM.User = user;

                Product prod = this._productHelper.VMToProduct(productVM, src);

                await this._repos.CreateAsync(prod);

                return RedirectToAction(nameof(Index));
            }
            return View(productVM);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var product = await this._repos.GetByIdAsync(id.Value);

            if (product == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            // envoi a la view un VM de product
            var productVM = this._productHelper.ToProductViewModel(product);

            return View(productVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductViewModel productVM)
        {
            if (id != productVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string src = productVM.ImageUrl;

                    if (productVM.ImageFile != null && productVM.ImageFile.Length > 0)
                    {
                        src = await this._productHelper.SaveImageAsync(productVM);
                    }

                    // check User
                    var user = await this._userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                    productVM.User = user;

                    var product = this._productHelper.VMToProduct(productVM, src);

                    await _repos.UpdateAsync(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this._repos.ExistAsync(productVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productVM);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var product = await this._repos.GetByIdAsync(id.Value);

            if (product == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            return View(product);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await this._repos.GetByIdAsync(id);
            await this._repos.DeleteAsync(product);

            return RedirectToAction(nameof(Index));
        }


        public IActionResult ProductNotFound()
        {
            return View();
        }
    }
}

Shop/Shop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Shop.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Produits</a></li>
                    <li><a asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>

            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Shop.Web</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>